export const eventConsts = {
    ON_EVENT_REQUESTED: 'ON_EVENT_REQUESTED',
    ON_EVENT_RECEIVED: 'ON_EVENT_RECEIVED',
    ON_EVENT_LOAD_FAILED: 'ON_EVENT_LOAD_FAILED',

    ON_ENTRY_CHANGE: 'ON_ENTRY_CHANGE'
}

export default eventConsts;